name: 'Secure Docker Login'
description: 'Logs into Quay using passed credentials without leaking password'
inputs:
  username:
    required: true
  password:
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "::add-mask::$INPUT_PASSWORD"
        echo "$INPUT_PASSWORD" | docker login quay.io -u "$INPUT_USERNAME" --password-stdin
      env:
        INPUT_USERNAME: ${{ inputs.username }}
        INPUT_PASSWORD: ${{ inputs.password }}
