name: Quay Login Securely

on:
  workflow_dispatch:
    inputs:
      quay_registry_username:
        description: 'Quay username'
        required: true
      quay_registry_password:
        description: 'Quay password'
        required: true
        type: password

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login securely using composite action
        uses: ./.github/actions/secure-login
        with:
          username: ${{ github.event.inputs.quay_registry_username }}
          password: ${{ github.event.inputs.quay_registry_password }}
