name: Quay Login Securely

on:
  workflow_dispatch:
    inputs:
      quay_registry_username:
        description: 'Quay username'
        required: true
      quay_registry_password:
        description: 'Quay password'
        required: true
        type: password

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Docker login to Quay (no secret leak)
        shell: bash
        run: |
          USERNAME="${{ github.event.inputs.quay_registry_username }}"
          PASSWORD=$(cat <<< "${{ github.event.inputs.quay_registry_password }}")

          echo "::add-mask::$PASSWORD"
          echo "$PASSWORD" | docker login quay.io -u "$USERNAME" --password-stdin
